services:
  hack_the_planet:
    container_name: hack_the_planet
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - hack_the_planet_network


networks:
  hack_the_planet_network:
    driver: bridge